module.exports = {
	branches: [
        { name: 'master' },
        { name: 'release', channel: 'release', prerelease: 'rc' },
	],
    tagFormat: '${version}.${env.GITHUB_RUN_NUMBER}${nextRelease.channel ? "-" + nextRelease.channel : ""}',
	plugins: [
		[
			'@semantic-release/commit-analyzer',
			{
				preset: 'conventionalcommits',
				presetConfig: {
					headerPattern: '.*',
				},
				releaseRules: [
					{ type: 'feat', release: 'minor' },
					{ type: 'fix', release: 'patch' },
					{ type: 'perf', release: 'patch' },
					{ type: 'revert', release: 'patch' },
					{ type: 'docs', release: false },
					{ type: 'style', release: false },
					{ type: 'test', release: false },
					{ type: 'ci', release: false },
					{ type: 'refactor', release: false },
					{ type: 'build', release: 'patch' },
					{ type: 'chore', release: 'patch' },
					{ scope: 'deps', release: 'minor' },
					{ breaking: true, release: 'major' },
				],
                defaultReleaseType: "patch",
				parserOpts: {
					noteKeywords: ['BREAKING CHANGE', 'BREAKING CHANGES'],
				},
			},
		],
		'@semantic-release/release-notes-generator',
		[
			'@semantic-release/changelog',
			{
				changelogFile: 'CHANGELOG.md',
				changelogTitle: '# 📦 Changelog',
			},
		],
		[
			'@semantic-release/git',
			{
				assets: ['package.json', 'package-lock.json', 'CHANGELOG.md'],
                message: [
                    'chore(release): ${nextRelease.version}.${env.GITHUB_RUN_NUMBER}${env.SEMANTIC_TAG_SUFFIX || ""} [skip ci]',
                    '',
                    '🔖 Release notes:',
                    '${nextRelease.notes}',
                    '',
                    'Generated by semantic-release 🚀',
                  ].join('\n'),
			},
		],
		[
			'@semantic-release/github',
			{
				assets: [{ path: 'CHANGELOG.md', label: 'Changelog' }],
				successComment: true,
				failComment: false,
				addLabels: true,
			},
		],
	],
};
