module.exports = {
	branches: [{ name: 'master' }, { name: 'release', channel: 'release', prerelease: 'rc' }],
	tagFormat: 'v${version}',
	plugins: [
		[
			'@semantic-release/commit-analyzer',
			{
				preset: 'conventionalcommits',
				presetConfig: {
					headerPattern: '.*',
				},
				releaseRules: [
					{ type: 'feat', release: 'minor' },
					{ type: 'fix', release: 'patch' },
					{ type: 'perf', release: 'patch' },
					{ type: 'revert', release: 'patch' },
					{ type: 'docs', release: false },
					{ type: 'style', release: false },
					{ type: 'test', release: false },
					{ type: 'ci', release: false },
					{ type: 'refactor', release: false },
					{ type: 'build', release: 'patch' },
					{ type: 'chore', release: 'patch' },
					{ type: '*', release: 'patch' },
					{ scope: 'deps', release: 'patch' },
					{ breaking: true, release: 'major' },
				],
				defaultReleaseType: 'patch',
				parserOpts: {
					noteKeywords: ['BREAKING CHANGE', 'BREAKING CHANGES'],
				},
			},
		],
		[
			'@semantic-release/release-notes-generator',
			{
				preset: 'conventionalcommits',
				presetConfig: {
					types: [
						{ type: 'feat', section: 'Features', hidden: false },
						{ type: 'fix', section: 'Bug Fixes', hidden: false },
						{ type: 'perf', section: 'Performance Improvements', hidden: false },
						{ type: 'revert', section: 'Reverts', hidden: false },
						{ type: 'docs', section: 'Documentation', hidden: false },
						{ type: 'style', section: 'Styles', hidden: false },
						{ type: 'chore', section: 'Miscellaneous Chores', hidden: false },
						{ type: 'refactor', section: 'Code Refactoring', hidden: false },
						{ type: 'test', section: 'Tests', hidden: false },
						{ type: 'build', section: 'Build System', hidden: false },
						{ type: 'ci', section: 'Continuous Integration', hidden: false },
					],
				},
			},
		],
		[
			'@semantic-release/changelog',
			{
				preset: 'conventionalcommits',
				changelogFile: 'CHANGELOG.md',
				changelogTitle: '# 📦 Changelog',
			},
		],
		[
			'@semantic-release/git',
			{
				assets: ['package.json', 'package-lock.json', 'CHANGELOG.md'],
				message: [
					'chore(release): ${nextRelease.gitTag} [skip ci]\n\n${nextRelease.notes}',
					'',
					'🔖 Release notes:',
					'${nextRelease.notes}',
					'',
					'Generated by semantic-release 🚀',
				].join('\n'),
			},
		],
		[
			'@semantic-release/github',
			{
				assets: [{ path: 'CHANGELOG.md', label: 'Changelog' }],
				releaseName: '${nextRelease.gitTag}',
				successCommentCondition: false,
				failComment: false,
				releasedLabels: false,
			},
		],
	],
};
