name: Build Application

on:
    workflow_dispatch:
    push:
        branches:
            - master

        tags: ['v*.*.*']

    pull_request:
        branches:
            - master
            - developed
            - feature/*
            - test/*
            - hotfix/*
            - fix/*
            - tech/
        types: [opened, synchronize, closed]

env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
    DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
    DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
    IS_MERGED: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged }}

jobs:
    check-merged:
        runs-on: ubuntu-latest
        outputs:
            is_merged: ${{ steps.check.outputs.is_merged }}
        steps:
            - name: Check if PR is merged
              id: check
              run: |
                  echo "is_merged=false" >> $GITHUB_ENV
                  if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
                    echo "is_merged=true" >> $GITHUB_ENV
                  fi
              shell: bash

    update-tag-version-if_merged:
        needs: check-merged
        if: ${{ needs.check-merged.outputs.is_merged == 'true' }}
        uses: ./.github/workflows/update_semver.yml

    build-ui:
        needs: check-merged
        if: ${{ needs.check-merged.outputs.is_merged != 'true' }}
        name: Angular UI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout & Bump tag version
              uses: ./.github/workflows/update_semver.yml

            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'
                  cache-dependency-path: package-lock.json

            - name: Upload & Install UI dependencies
              run: |
                  npm ci

            - name: Build UI project
              run: |
                  npm run build-prod --if-present

            - name: Run UI tests
              run: |
                  npm run test-headless

            - name: Run sonnarqube
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  npm run sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}

            - name: Enquire last git tag
              id: last_tag
              shell: bash
              run: |
                  tag_v=$(git describe --tags $(git rev-list --tags --max-count=1))
                  tag=$(echo $tag_v | sed 's/v//')

                  echo "TARGET_TAG=${tag}" >> $GITHUB_OUTPUT

            - name: Set up 'Find Current Pull Request'
              uses: jwalton/gh-find-current-pr@v1
              id: findPr
              with:
                  # Can be "open", "closed", or "all".  Defaults to "open".
                  state: open

            - name: Build docker image
              env:
                  GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
                  GITHUB_RUN_ID: ${{ github.run_id }}
                  RUN_NUMBER: ${{ github.run_number }}
                  RUN_ATTEMPT: ${{ github.run_attempt }}
                  PULL_REQUEST_ID: ${{ steps.findPr.outputs.pr }}
                  PULL_REQUEST_SOURCE_BRANCH: ${{ github.ref }}
                  PULL_REQUEST_TARGET_BRANCH: refs/heads/master
                  ACTION: ${{ github.action }}
                  EVENT_NAME: ${{ github.event_name }}
              shell: bash
              run: |

                  echo "latest tag is ${{ steps.last_tag.outputs.TARGET_TAG }}"

                  docker build \
                  --target 'publish' -t "${{ env.DOCKERHUB_USERNAME }}/homebudget-ui:${{ steps.last_tag.outputs.TARGET_TAG }}" \
                  --build-arg PULL_REQUEST_ID='${{ steps.findPr.outputs.pr }}' \
                  --build-arg PULL_REQUEST_SOURCE_BRANCH='${{ github.ref }}' \
                  --build-arg PULL_REQUEST_TARGET_BRANCH=refs/heads/master \
                  --build-arg GITHUB_RUN_ID='${{ github.run_id }}' \
                  --build-arg SONAR_TOKEN='${{ env.SONAR_TOKEN }}' \
                  .

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push docker image
              shell: bash
              run: |
                  docker push "${{ secrets.DOCKERHUB_USERNAME }}/homebudget-ui:${{ steps.last_tag.outputs.TARGET_TAG }}"
