name: Deployment on environment (GitHub)

on:
  workflow_call:
    inputs:
      last_tag:
        required: true
        type: string
      pr_number:
        required: false
        type: string
      is_merged:
        required: true
        type: boolean

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://hub.docker.com/r/${{ env.DOCKERHUB_USERNAME }}/homebudget-ui

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Deployment
        uses: actions/github-script@v7
        id: create-deployment
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              auto_merge: false,
              required_contexts: [],
              environment: 'production',
              transient_environment: false,
              production_environment: true,
              description: "Deploying Docker image for tag ${{ inputs.last_tag }}"
            });
            return deployment.data.id;

      - name: Build Docker image
        run: |
          echo "Building Docker image for tag: ${{ inputs.last_tag }}"
          docker build \
            --target publish \
            -t "${{ env.DOCKERHUB_USERNAME }}/homebudget-ui:${{ inputs.last_tag }}" \
            --build-arg PULL_REQUEST_ID="${{ inputs.pr_number }}" \
            --build-arg PULL_REQUEST_SOURCE_BRANCH="${{ github.ref }}" \
            --build-arg PULL_REQUEST_TARGET_BRANCH="refs/heads/master" \
            --build-arg GITHUB_RUN_ID="${{ github.run_id }}" \
            --build-arg SONAR_TOKEN="${{ env.SONAR_TOKEN }}" \
            .

      - name: Login to Docker Hub
        if: ${{ inputs.is_merged == true }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: ${{ inputs.is_merged == true }}
        run: |
          echo "Pushing image to Docker Hub..."
          docker push "${{ env.DOCKERHUB_USERNAME }}/homebudget-ui:${{ inputs.last_tag }}"

      - name: Update Deployment Status - Success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.create-deployment.outputs.result }},
              state: 'success',
              environment_url: 'https://hub.docker.com/r/${{ env.DOCKERHUB_USERNAME }}/homebudget-ui'
            });

      - name: Update Deployment Status - Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.create-deployment.outputs.result }},
              state: 'failure'
            });