name: Release - Generate Tag and Changelog

on:
    push:
        branches:
            - master

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
    semantic-release:
        name: Generate Semantic Tag and Change log
        uses: ./.github/workflows/sem-release.yml
        secrets: inherit