name: Update Nuget packages

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest
    environment: CI
    name: Update dependencies
    steps:
      - name: Nukeeper
        env:
          NUKEEPER_TOKEN: ${{ secrets.NUKEEPER_TOKEN }}
        id: nukeeper
        uses: nukeeperdotnet/nukeeper-action@0.1
        with:
          token: "${{ secrets.NUKEEPER_TOKEN}}"
