name: Semantic Release

on:
    workflow_call:

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          token: ${{ env.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Sync master
        if: github.ref == 'refs/heads/master'
        run: |
          git fetch origin master
          git reset --hard origin/master

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        with:
            semantic_version: 23
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
