name: Manage versions
on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        issues: write
        repository-projects: write
        contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Version Bumper
        uses: michmich112/version-bumper@1.2.4
        with:
          options-file: "./.github/workflows/sem-ver-options.json"
          github-token: ${{ env.GITHUB_TOKEN }}
