name: Manage versions

on:
    push:
        branches:
            - master
            - develop
            - release
            - feature/*
            - test/*
            - hotfix/*
            - fix/*
            - tech/*
        tags:
            - 'v*'

    pull_request:
        branches:
            - master
            - release
            - feature/*
            - hotfix/*
        types: [closed]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    bump:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            issues: write
            repository-projects: write
            contents: write

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  lfs: true
                  token: ${{ env.GITHUB_TOKEN }}

            - name: Use Node.js 21.x
              uses: actions/setup-node@v4
              with:
                  node-version: '21'
                  cache: 'npm'
                  cache-dependency-path: package-lock.json

            - name: Version Bumper
              uses: michmich112/version-bumper@1.2.4
              with:
                  options-file: './.github/workflows/sem-ver-options.json'
                  github-token: ${{ env.GITHUB_TOKEN }}
